### ISSUE TITLE
lein-figwheel support

### ISSUE THREAD

**Issue by jeaye** [Olical/propel#2]
Hey @Olical! I've been using conjure for a while and it's superb (in fact, it's the **first** time I've had a good experience with a REPL-like plugin for Clojure in Vim); thanks for cooking up propel to help with the setup. One reason I don't yet have conjure working on our CLJS front-end is that the only docs you mentioned, in your blog, are for setup with Figwheel Main. However, we're not yet using Figwheel Main, since it makes some certain assumptions about file paths which don't work with how we were using lein-figwheel.

I've noticed that the docs for propel also only mention Figwheel Main, so I'm hoping you can provide some info as to how propel can be used with lein-figwheel. Now, before you say "everyone should be using Figwheel Main", I want to quote propel's own README:

> It should only contain things 95% of people should find useful early on in a project.

[lein-figwheel](https://clojars.org/lein-figwheel) has over 1 million downloads with around 67 thousand downloads the past two versions. [figwheel-main](https://clojars.org/com.bhauman/figwheel-main), however, has a total of 42 thousand downloads, with fewer than 700 the past two versions. So, just looking at the past two versions, lein-figwheel still has 99% of the users.

Is that convincing enough to help a brother out? :)

**Comment by Olical** [comment]
Hello! Thank you so much for the kind words, it means a lot! I hope I continue to improve these tools for you and whoever you also convince to come over to the Vim side :stuck_out_tongue:

I'm having a think about this, it's a completely fair shout, you make a good point with statistics too! You're a few slides short of a full on presentation, impressive.

I'll have a dig into lein-figwheel and see if it exposes anything I can work with, I'm guessing it will. I might be able to provide a function / argument within Propel that lets you hook up an already running environment such as something started by `lein figwheel` :thinking:

I'll get back to you on this soon, as long as I can ask lein-figwheel for it's ClojureScript evaluation environment like I do with figwheel-main it should be fine. I just might not be able to start the figwheel environment itself, which is probably totally fine given the context.

**Comment by Olical** [comment]
In the interest of helping you quicker, you might find the answer in the figwheel-main approach + working out how to get the ClojureScript evaluation environment from lein-figwheel, which is all I'm going to try and do anyway.

I'm _guessing_ it's what tools such as figwheel-sidecar do? So I assume it's possible to ask figwheel for this. I'm :ok_hand: this close to messaging Bruce but I'll try to work it out myself first!

**Comment by Olical** [comment]
My week off is looming, today is my last day at my current job. This issue is not forgotten and will be squashed 😊 I hope you're having a good week!

**Comment by jeaye** [comment]
Thanks for the follow up, Oliver! I hope you enjoy the new opportunities and I'm looking forward to what else you cook up. :smile:

**Comment by Olical** [comment]
This is implemented on master, if you have a chance to try it with an existing project I'd love to hear if it works or not :smile:

**Comment by Olical** [comment]
Released in `v1.1.0`, just execute with `-e lein-figwheel` :tada:

**Comment by jeaye** [comment]
Hey @Olical! I'm very excited to see this. Thank you so much for working on it.

Based on what I'm reading in the docs, this requires `deps.edn`, right? I think it's fair to say the vast majority of people are using leiningen, but maybe that's not so much an issue, since I think I can just add a `deps.edn` solely for Propel. Based on my testing, that's enough to get Propel up and running with a prepl.

Alas, things are not so easy for non-trivial projects. Our project, for example (building [OkLetsPlay](https://okletsplay.com)), is started something like this:

```bash
$ lein electron-figwheel
```

Behind the scenes, that's a leiningen alias defined as follows:

```clojure
:aliases {"electron-figwheel" ["with-profile" "+electron" "trampoline" "figwheel" "electron-entry" "electron"]}
```

In this case, figwheel spins up and watches two different builds (we care about a prepl for only one of them) and also relies very much on leiningen profiles in order to configure things. So, having Propel be outside of leiningen ends up being a much larger problem.

I think, going forward, a better solution here is to not assume anything about the build tool and instead just allow people to use the `propel.core` ns to spin things up as needed. However, with leiningen, figwheel, and `propel.core`, I'm not sure of what to actually do. I've tried creating a `user.clj` with something like this:

```clojure
(ns user
  (:require [propel.core]))

(propel.core/start-prepl! {:env :lein-figwheel
                           :port 5555})
```

This fails, though, since the only way we have in place to start this up is through Figwheel, but Propel is expecting to start Figwheel on its own, so they conflict and Propel fails since the Figwheel port is in use.

What would really remedy this is if there could be some code devs can add to a project which attaches to the existing Figwheel data. Or, perhaps I'm just missing something simple and this already works with the leiningen-style approach.

Finally, is the Figwheel I start up through Propel (CLI or fns) going to use the appropriate Figwheel configuration I have specified in my `project.clj`?

**Comment by Olical** [comment]
Oh no, it doesn't require `deps.edn` as far as I'm aware? Maybe there's a bug or the docs are wrong if so?

And I feel like this is a bigger problem, the `lein-figwheel` env will simply execute the figwheel sidecar start function which will read your `project.clj` and decide what to start for itself. It then asks for the REPL env from figwheel, I don't specify which, I presume it just selects the first.

I think this is enough for simple figwheel setups, for any complex setup I feel like so many arguments will be required that propel will end up a tangled mess, which is something I'm really trying to avoid. I think for most people, what I've added will be enough for the start of their project with one figwheel config.

For your case, I'd recommend you do what propel is doing yourself, something like this:

```clojure
(require '[figwheel-sidecar.repl-api :as fig]
               '[clojure.core.server :as server])

;; Start the prepl server with the figwheel repl env.
(server/start-server
  {:name "my-prepl"
    :address "127.0.0.1"
    :port 5555
    :accept 'cljs.core.server/io-prepl
    :args [:repl-env (fig/repl-env "my-fig-env")]})

;; Drop into a ClojureScript REPL.
(fig/cljs-repl "my-fig-env")
```

I think that'll be enough to hook it up for you? Maybe I need to make propel's source more literate so that people can find this sort of thing, I'd love for it to be a rosetta stone of sorts that you can execute for some simple cases, if that makes sense?

**Comment by jeaye** [comment]
Thank you, @Olical, for the explanation. :) I understand you don't want to over complicate Propel, so we won't likely be supporting non-trivial leiningen setups with it.

If I understand correctly, I would set up both the figwheel REPL and the prepl in my `user.clj`. However, I'm not having much luck doing so:

```clojure
(ns user
  (:require [figwheel-sidecar.repl-api :as fig]
            [clojure.core.server :as server]))

; Start Figwheel.
(fig/start-figwheel! "electron-entry" "electron")

; Start the prepl server with the figwheel repl env.
(server/start-server {:name "front-end"
                      :address "127.0.0.1"
                      :port 5555
                      :accept 'cljs.core.server/io-prepl
                      :args [:repl-env (fig/repl-env "my-fig-env")]})

; Drop into a ClojureScript REPL.
(fig/cljs-repl "my-fig-env")
```

Given the above, I would think I can do something like `lein with-profile +electron repl` and have Figwheel start, along with my prepl. Unfortunately, it seems Figwheel can only see the first build id (and no others) when I do this, so I'm not actually able to start up my multiple builds. I may be over extending both my welcome and your knowledge here, but do you have any additional tips for getting this working?

Thank you. :slightly_smiling_face:

**Comment by Olical** [comment]
Hmm yeah, might be surpassing what I know about lein internals, Bruce might be a better person to ping about this 😅 the prepl part is pretty straight forward I think? You just give it an env. 

It's the figwheel part I'm really not sure about. Although now that I look at the source, I'm not sure if you can pass multiple ids to `start-figwheel!`, maybe try to make it look more like the example in the readme?

```clojure
(require
 '[figwheel-sidecar.repl-api :as ra])

(defn start []
  (ra/start-figwheel!
    {:figwheel-options {} ;; <-- figwheel server config goes here 
     :build-ids ["dev"]   ;; <-- a vector of build ids to start autobuilding
     :all-builds          ;; <-- supply your build configs here
     [{:id "dev"
       :figwheel true
       :source-paths ["src"]
       :compiler {:main "example.core"
                  :asset-path "out"
                  :output-to "resources/public/main.js"
                  :output-dir "resources/public/out"
                  :verbose true}}]}))

;; Please note that when you stop the Figwheel Server http-kit throws
;; a java.util.concurrent.RejectedExecutionException, this is expected

(defn stop []
  (ra/stop-figwheel!))

(defn repl []
  (ra/cljs-repl))
```
